export const DEMO_PROFILE = {
  education_stage: "class_12",
  stream: "science_pcm",
  current_marks: "80-90%",
  institution_name: "Delhi Public School, R.K. Puram",
  interests: ["Technology", "Engineering", "Design", "Entrepreneurship"],
  current_skills: ["Python", "Mathematics", "Problem Solving", "Physics"],
  goal_type: "Get into a top college",
  budget_range: "₹5-15 lakh",
  timeline: "1-2 years",
  career_goals: "Build scalable software applications and specialize in AI engineering.",
  extra_context: "Interested in top Indian tech universities and startup culture in Bengaluru.",
};

export const DEMO_RECOMMENDATIONS = [
  {
    id: "demo-rec-1",
    user_id: "demo-user",
    career_title: "AI & Machine Learning Engineer",
    description:
      "Design and deploy intelligent algorithms, neural networks, and automated reasoning models for high-scale applications.",
    match_score: 94,
    salary_range: "₹12 - ₹35 LPA",
    growth_outlook: "Very High Demand",
    required_skills: [
      "Python",
      "Mathematics",
      "Machine Learning",
      "PyTorch",
      "Data Structures",
      "System Design",
    ],
    colleges: [
      {
        name: "IIT Bombay",
        course: "B.Tech Computer Science & Engineering",
        city: "Mumbai, Maharashtra",
        fees_total: "₹8.5 Lakhs (4 Years)",
        entrance: "JEE Advanced",
        why: "Top tier AI labs and strongest tech placements in India.",
      },
      {
        name: "BITS Pilani",
        course: "B.E. Computer Science",
        city: "Pilani, Rajasthan",
        fees_total: "₹22 Lakhs (4 Years)",
        entrance: "BITSAT",
        why: "Exceptional startup culture and zero attendance requirement allowing deep project work.",
      },
    ],
    is_saved: true,
    is_dismissed: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-rec-2",
    user_id: "demo-user",
    career_title: "Full Stack Systems Architect",
    description:
      "Architect resilient cloud software systems, backend APIs, and modern reactive web applications.",
    match_score: 88,
    salary_range: "₹10 - ₹28 LPA",
    growth_outlook: "High Demand",
    required_skills: ["Python", "TypeScript", "React", "Node.js", "PostgreSQL", "Cloud Computing"],
    colleges: [
      {
        name: "IIIT Hyderabad",
        course: "B.Tech Computer Science & Engineering",
        city: "Hyderabad, Telangana",
        fees_total: "₹14 Lakhs (4 Years)",
        entrance: "JEE Main / SPEC",
        why: "Renowned coding curriculum with early undergraduate research focus.",
      },
    ],
    is_saved: false,
    is_dismissed: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-rec-3",
    user_id: "demo-user",
    career_title: "Robotics & Embedded Systems Specialist",
    description:
      "Combine hardware programming, IoT sensors, and autonomous control software for next-gen automation.",
    match_score: 82,
    salary_range: "₹8 - ₹22 LPA",
    growth_outlook: "Moderate Growth",
    required_skills: ["Mathematics", "C++", "ROS", "Microcontrollers", "Control Systems"],
    colleges: [
      {
        name: "NIT Trichy",
        course: "B.Tech Instrumentation & Control",
        city: "Tiruchirappalli, Tamil Nadu",
        fees_total: "₹6.5 Lakhs (4 Years)",
        entrance: "JEE Main",
        why: "Outstanding robotics labs and national competition teams.",
      },
    ],
    is_saved: false,
    is_dismissed: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_MILESTONES = [
  {
    id: "demo-m-1",
    user_id: "demo-user",
    recommendation_id: "demo-rec-1",
    title: "Master Advanced Mathematics & Physics Foundations",
    description:
      "Focus on calculus, linear algebra, and coordinate geometry for JEE and entrance prep.",
    order_index: 0,
    category: "Phase 1: Foundation",
    status: "completed",
    target_date: "Month 1-3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-m-2",
    user_id: "demo-user",
    recommendation_id: "demo-rec-1",
    title: "Build Data Structures & Algorithms Core in Python/C++",
    description:
      "Solve 150+ problems on LeetCode covering arrays, trees, dynamic programming, and graphs.",
    order_index: 1,
    category: "Phase 1: Foundation",
    status: "in_progress",
    target_date: "Month 4-6",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-m-3",
    user_id: "demo-user",
    recommendation_id: "demo-rec-1",
    title: "Cracking Entrance Exams (JEE Main & BITSAT)",
    description: "Complete full-length mock tests and analyze weak areas systematically.",
    order_index: 2,
    category: "Phase 2: Exam & Admission",
    status: "pending",
    target_date: "Month 7-12",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-m-4",
    user_id: "demo-user",
    recommendation_id: "demo-rec-1",
    title: "Deploy First End-to-End Deep Learning Model",
    description:
      "Train a computer vision or LLM model using PyTorch and host it with FastAPI on Cloud.",
    order_index: 3,
    category: "Phase 3: Specialization",
    status: "pending",
    target_date: "Year 2",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
